### ISSUE TITLE
Keyboard key input not working properly

### ISSUE THREAD

**Issue by PuneetTri** [dekuxdseek/Notes#1]
I came across this project and found it quite interesting, as a result i downloaded the souce code. But I've found it not quite working as advertised. It seems like keyboard input is not working properly, no sounds are emmited upon keystrokes.
I request you to modify your code and get it working. Cheers!

**Comment by dekuxdseek** [comment]
hey, thanks for pointing the fault out, I have corrected the code, I forgot to call makeSound(), for keystrokes. I really appreciate your feedback.
